version: "2"

linters:
  enable:
    - unused
    - staticcheck
    - ineffassign
    - govet
    - whitespace

  settings:
    whitespace:
      multi-func: false
      multi-if: false

run:
  tests: false